# Generated by Django 2.1.2 on 2018-10-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_added_result_ttl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjob',
            name='cron_string',
            field=models.CharField(help_text='Define the schedule in a crontab like syntax. Times are in UTC.',
                                   max_length=64, verbose_name='cron string'),
        ),
        migrations.AlterField(
            model_name='repeatablejob',
            name='interval_unit',
            field=models.CharField(choices=[('seconds', 'seconds'), ('minutes', 'minutes'), ('hours', 'hours'), ('days', 'days'), ('weeks', 'weeks')], default='hours', max_length=12, verbose_name='interval unit'),
        ),
    ]
