# Generated by Django 2.0.6 on 2018-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_added_result_ttl'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjob',
            name='callable_args',
            field=models.CharField(blank=True, max_length=2048, verbose_name='args'),
        ),
        migrations.AddField(
            model_name='cronjob',
            name='callable_kwargs',
            field=models.CharField(blank=True, max_length=2048, verbose_name='kwargs'),
        ),
        migrations.AddField(
            model_name='repeatablejob',
            name='callable_args',
            field=models.CharField(blank=True, max_length=2048, verbose_name='args'),
        ),
        migrations.AddField(
            model_name='repeatablejob',
            name='callable_kwargs',
            field=models.CharField(blank=True, max_length=2048, verbose_name='kwargs'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='callable_args',
            field=models.CharField(blank=True, max_length=2048, verbose_name='args'),
        ),
        migrations.AddField(
            model_name='scheduledjob',
            name='callable_kwargs',
            field=models.CharField(blank=True, max_length=2048, verbose_name='kwargs'),
        ),
    ]
