# Generated by Django 2.2.2 on 2019-06-03 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduler', '0006_seconds_interval_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobKwarg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_type', models.CharField(choices=[('str_val', 'string'), ('int_val', 'int'), ('bool_val', 'boolean'), ('datetime_val', 'Datetime')], default='str_val', max_length=12, verbose_name='Argument Type')),
                ('str_val', models.CharField(blank=True, max_length=255, verbose_name='String Value')),
                ('int_val', models.IntegerField(blank=True, null=True, verbose_name='Int Value')),
                ('bool_val', models.BooleanField(default=False, verbose_name='Boolean Value')),
                ('datetime_val', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Value')),
                ('object_id', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_type', models.CharField(choices=[('str_val', 'string'), ('int_val', 'int'), ('bool_val', 'boolean'), ('datetime_val', 'Datetime')], default='str_val', max_length=12, verbose_name='Argument Type')),
                ('str_val', models.CharField(blank=True, max_length=255, verbose_name='String Value')),
                ('int_val', models.IntegerField(blank=True, null=True, verbose_name='Int Value')),
                ('bool_val', models.BooleanField(default=False, verbose_name='Boolean Value')),
                ('datetime_val', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Value')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
