# Generated by Django 2.0.7 on 2018-07-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduler', '0006_added_args_kwargs'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobArg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_val', models.CharField(blank=True, max_length=255, verbose_name='String Value')),
                ('int_val', models.IntegerField(blank=True, null=True, verbose_name='Int Value')),
                ('datetime_val', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Value')),
                ('arg_name', models.CharField(choices=[('str_val', 'string'), ('int_val', 'int'), ('datetime_val', 'Datetime')], default='str_val', max_length=12, verbose_name='Argument Type')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobKwarg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_val', models.CharField(blank=True, max_length=255, verbose_name='String Value')),
                ('int_val', models.IntegerField(blank=True, null=True, verbose_name='Int Value')),
                ('datetime_val', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Value')),
                ('arg_name', models.CharField(choices=[('str_val', 'string'), ('int_val', 'int'), ('datetime_val', 'Datetime')], default='str_val', max_length=12, verbose_name='Argument Type')),
                ('object_id', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='callable_args',
        ),
        migrations.RemoveField(
            model_name='cronjob',
            name='callable_kwargs',
        ),
        migrations.RemoveField(
            model_name='repeatablejob',
            name='callable_args',
        ),
        migrations.RemoveField(
            model_name='repeatablejob',
            name='callable_kwargs',
        ),
        migrations.RemoveField(
            model_name='scheduledjob',
            name='callable_args',
        ),
        migrations.RemoveField(
            model_name='scheduledjob',
            name='callable_kwargs',
        ),
    ]
